default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: xyz-books-development

test:
  <<: *default
  database: xyz-books-test

production:
  <<: *default
  database: xyzbooks
  username: msongco
  password: <%= ENV["DATABASE_PASSWORD"] %>
  url: <%= ENV["DATABASE_URL"] %>